package com.eat.erp;

import android.util.Log;

public class OrdersData {
    public static String channel_type;
    public static String distributor_type;
    public static String distributor_name;
    public static String zone_id;
    public static String zone;
    public static String area_id;
    public static String area;
    public static String location_id;
    public static String location;
    public static String remarks;
    public static String longitude;
    public static String latitude;
    public static String distributor_id;
    public static String mid;
    public static String reation_id;
    public static String reation;
    public static String beat_plan_id;
    public static String store_id;
    public static String distributor_status;
    public static String sales_rep_loc_id;
    public static String sequence;
    public static String follow_type;
    public static String merchandiser_stock_id;
    public static String chocolate_cookies_box;
    public static String dark_chocolate_cookies_box;
    public static String cranberry_cookies_box;
    public static String cranberry_orange_box;
    public static String fig_raisins_box;
    public static String papaya_pineapple_box;
    public static String orange_bar;
    public static String orange_box;
    public static String butterscotch_bar;
    public static String butterscotch_box;
    public static String chocopeanut_bar;
    public static String chocopeanut_box;
    public static String bambaiyachaat_bar;
    public static String bambaiyachaat_box;
    public static String mangoginger_bar;
    public static String mangoginger_box;
    public static String berry_blast_bar;
    public static String berry_blast_box;
    public static String chyawanprash_bar;
    public static String chyawanprash_box;
    public static String variety_box;
    public static String margin;
    public static String retailer_remarks;
    public static String gst_number;
    public static String order_chocolate_cookies_box;
    public static String order_dark_chocolate_cookies_box;
    public static String order_cranberry_cookies_box;
    public static String order_cranberry_orange_box;
    public static String order_fig_raisins_box;
    public static String order_papaya_pineapple_box;
    public static String order_orange_bar;
    public static String order_orange_box;
    public static String order_butterscotch_bar;
    public static String order_butterscotch_box;
    public static String order_chocopeanut_bar;
    public static String order_chocopeanut_box;
    public static String order_bambaiyachaat_bar;
    public static String order_bambaiyachaat_box;
    public static String order_mangoginger_bar;
    public static String order_mangoginger_box;
    public static String order_berry_blast_bar;
    public static String order_berry_blast_box;
    public static String order_chyawanprash_bar;
    public static String order_chyawanprash_box;
    public static String order_variety_box;
    public static String order_remarks;
    public static String order_flag;
    public static String ispermenant;
    public static String chocolate_cookies_json;
    public static String dark_chocolate_cookies_json;
    public static String cranberry_cookies_json;
    public static String cranberry_orange_json;
    public static String fig_raisins_json;
    public static String papaya_pineapple_json;
    public static String orange_bar_json;
    public static String orange_box_json;
    public static String butterscotch_bar_json;
    public static String butterscotch_box_json;
    public static String chocopeanut_bar_json;
    public static String chocopeanut_box_json;
    public static String bambaiyachaat_bar_json;
    public static String bambaiyachaat_box_json;
    public static String mangoginger_bar_json;
    public static String mangoginger_box_json;
    public static String berry_blast_bar_json;
    public static String berry_blast_box_json;
    public static String chyawanprash_bar_json;
    public static String chyawanprash_box_json;
    public static String variety_box_json;
    public static String batch_no_json;
    public static String actual_count;
    public static String p_call;
    public static String unplanned_count;
    public static String total_count;
    public static String order_bars;
    public static String order_cookies;
    public static String order_trailmix;
    public static String reporting_manager;
    public static String batch_details;

    public void clear() {
        Log.e("ordersdata", "cleared");
        channel_type = null;
        channel_type = null;
        distributor_type = null;
        distributor_name = null;
        zone_id = null;
        zone = null;
        area_id = null;
        area = null;
        location_id = null;
        location = null;
        remarks = null;
        longitude = null;
        latitude = null;
        distributor_id = null;
        mid = null;
        reation_id = null;
        reation = null;
        beat_plan_id = null;
        store_id = null;
        distributor_status = null;
        sales_rep_loc_id = null;
        sequence = null;
        follow_type = null;
        merchandiser_stock_id = null;
        chocolate_cookies_box = null;
        dark_chocolate_cookies_box = null;
        cranberry_cookies_box = null;
        cranberry_orange_box = null;
        fig_raisins_box = null;
        papaya_pineapple_box = null;
        orange_bar = null;
        orange_box = null;
        butterscotch_bar = null;
        butterscotch_box = null;
        chocopeanut_bar = null;
        chocopeanut_box = null;
        bambaiyachaat_bar = null;
        bambaiyachaat_box = null;
        mangoginger_bar = null;
        mangoginger_box = null;
        berry_blast_bar = null;
        berry_blast_box = null;
        chyawanprash_bar = null;
        chyawanprash_box = null;
        variety_box = null;
        margin = null;
        retailer_remarks = null;
        gst_number = null;
        order_chocolate_cookies_box = null;
        order_dark_chocolate_cookies_box = null;
        order_cranberry_cookies_box = null;
        order_cranberry_orange_box = null;
        order_fig_raisins_box = null;
        order_papaya_pineapple_box = null;
        order_orange_bar = null;
        order_orange_box = null;
        order_butterscotch_bar = null;
        order_butterscotch_box = null;
        order_chocopeanut_bar = null;
        order_chocopeanut_box = null;
        order_bambaiyachaat_bar = null;
        order_bambaiyachaat_box = null;
        order_mangoginger_bar = null;
        order_mangoginger_box = null;
        order_berry_blast_bar = null;
        order_berry_blast_box = null;
        order_chyawanprash_bar = null;
        order_chyawanprash_box = null;
        order_variety_box = null;
        order_remarks = null;
        order_flag = null;
        ispermenant = null;
        chocolate_cookies_json=null;
        dark_chocolate_cookies_json=null;
        cranberry_cookies_json=null;
        cranberry_orange_json=null;
        fig_raisins_json=null;
        papaya_pineapple_json=null;
        orange_bar_json=null;
        orange_box_json=null;
        butterscotch_bar_json=null;
        butterscotch_box_json=null;
        chocopeanut_bar_json=null;
        chocopeanut_box_json=null;
        bambaiyachaat_bar_json=null;
        bambaiyachaat_box_json=null;
        mangoginger_bar_json=null;
        mangoginger_box_json=null;
        berry_blast_bar_json=null;
        berry_blast_box_json=null;
        chyawanprash_bar_json=null;
        chyawanprash_box_json=null;
        variety_box_json=null;
        batch_details=null;

    }

}
